draftkings/draftkings/urls.py
from django.conf.urls import url
from django.contrib import admin

from basketball.views import (
    PlayerDetail,
    HomeView,
    PlayerList,
    TeamDetail,
    TeamList,
    GameDetail,
    ELOView,
    CustomLineupView,
    ContestListView,
    ContestDetailView,
)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^players/$', PlayerList.as_view(), name='players'),
    url(r'^players/(?P<pk>[0-9]+)/', PlayerDetail.as_view(), name='player'),
    url(r'^teams/$', TeamList.as_view(), name='teams'),
    url(r'^teams/(?P<pk>[0-9]+)/', TeamDetail.as_view(), name='team'),
    url(r'^games/(?P<pk>[0-9]+)/', GameDetail.as_view(), name='game'),
    url(r'^tools/elo/', ELOView.as_view(), name='elo'),
    url(r'^tools/custom-lineup/', CustomLineupView.as_view(), name='custom_lineup'),
    url(r'^contests/', ContestListView.as_view(), name='contests'),
    url(r'^contest/(?P<pk>[0-9]+)/', ContestDetailView.as_view(), name='contest'),
]

draftkings/basketball/models.py
from __future__ import unicode_literals
import itertools

from datetime import datetime, timedelta
import six

from django.db import models
from django.db.models import Q
from django.conf import settings


class Season(models.Model):
    name_choices = (
        ('14', '14-15'),
        ('15', '15-16'),
        ('16', '16-17'),)

    name = models.CharField(max_length=2, choices=name_choices)
    scrape_id = models.IntegerField(null=True, blank=True, unique=True)

    def __str__(self):
        return self.scrape_string()

    def start_year(self):
        return 2000 + int(six.text_type(self.name))

    def end_year(self):
        return 2001 + int(six.text_type(self.name))

    def scrape_string(self):
        first_part = 2000 + int(six.text_type(self.name))
        second_part = int(six.text_type(self.name)) + 1
        return '-'.join([str(first_part), str(second_part)])

    def year_for_date(self, date):
        if date.month > 8:
            return 2000 + int(six.text_type(self.name))
        else:
            return 2001 + int(six.text_type(self.name))


class GameManager(models.Manager):

    def games_for_team(self, team):
        if isinstance(team, six.string_types):
            if len(team) <= 3:
                q = Q(away_team__short=team) | Q(home_team__short=team)
            else:
                q = Q(away_team__name=team) | Q(home_team__name=team)
        elif isinstance(team, Team):
            q = Q(away_team=team) | Q(home_team=team)
        else:
            q = Q(away_team__pk=team) | Q(home_team__pk=team)
        return self.filter(q).order_by('date')


class Game(models.Model):
    scrape_id = models.IntegerField(null=True, blank=True, unique=True)
    date = models.DateTimeField()
    season = models.ForeignKey('Season', related_name='games')
    home_team = models.ForeignKey('Team', related_name='home_games', null=True, blank=True)
    away_team = models.ForeignKey('Team', related_name='away_games', null=True, blank=True)
    home_elo = models.IntegerField(default=0)
    away_elo = models.IntegerField(default=0)
    elo_applied = models.BooleanField(default=False)

    objects = GameManager()

    def __str__(self):
        return '{teams} {date}'.format(
            teams='{} v {}'.format(self.home_team, self.away_team),
            date=self.date.date())

    def home_team_score(self):
        game_logs = GameLog.objects.filter(
            game=self,
            team=self.home_team)
        return sum(gl.points for gl in game_logs)

    def away_team_score(self):
        game_logs = GameLog.objects.filter(
            game=self,
            team=self.away_team)
        return sum(gl.points for gl in game_logs)

    def winner(self):
        if self.home_team_score() > self.away_team_score():
            return self.home_team
        else:
            return self.away_team

    def home_team_previous_game(self):
        return Game.objects.filter(
            home_team=self.home_team,
            date__lt=self.date).order_by('-date').first()

    def away_team_previous_game(self):
        return Game.objects.filter(
            home_team=self.home_team,
            date__lt=self.date).order_by('-date').first()

    def elo_for_team(self, team):
        if team.pk == self.home_team.pk:
            return self.home_elo
        return self.away_elo


class Team(models.Model):
    scrape_id = models.IntegerField(null=True, blank=True, unique=True)
    city = models.CharField(max_length=20)
    name = models.CharField(max_length=20, unique=True)
    abbreviation = models.CharField(max_length=4, unique=True)
    elo = models.IntegerField(default=1500)

    def set_of_all_players(self):
        return {gl.player for gl in GameLog.objects.filter(team=self)}

    def __str__(self):
        return self.name

    def average_points(self, game_logs=None):
        game_stats = self.game_logs_grouped_by_game(game_logs=game_logs)
        if len(game_stats):
            return sum(s.draft_king_points for s in itertools.chain(*game_stats)) / len(game_stats)
        return 0

    def average_playtime(self, game_logs=None):
        game_stats = self.game_logs_grouped_by_game(game_logs=game_logs)
        if len(game_stats):
            return sum(s.minutes for s in itertools.chain(*game_stats)) / len(game_stats)
        return 0

    def game_logs(self):
        return GameLog.objects.filter(team=self)

    def game_logs_grouped_by_game(self, game_logs=None):
        games = Game.objects.games_for_team(self)
        return_value = []
        for game in games:
            if game_logs is not None:
                team_game_logs = game_logs.filter(game=game, team=self)
            else:
                team_game_logs = GameLog.objects.filter(game=game, team=self)

            if team_game_logs:
                return_value.append(team_game_logs)

        return return_value


class Player(models.Model):
    scrape_id = models.IntegerField(null=True, blank=True, unique=True)

    name = models.CharField(max_length=40)
    current_team = models.ForeignKey('Team', related_name='players')
    games = models.ManyToManyField('Game', through='GameLog')

    position = models.CharField(max_length=2, null=True, blank=True)
    birthday = models.DateField(null=True, blank=True)
    weight = models.IntegerField(null=True, blank=True)  # kg
    height = models.IntegerField(null=True, blank=True)  # cm
    games_started = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.name

    @property
    def age(self):
        today = datetime.today()
        return today.year - self.birthday.year - ((today.month, today.day) < (self.birthday.month, self.birthday.day))

    def game_logs_since_date(self, date, from_date=None):
        if not from_date:
            from_date = datetime.now().date()

        return (
            self.gamelog_set
                .filter(game__date__gte=date)
                .filter(game__date__lte=from_date)
                .order_by('-game__date'))

    def game_logs_before_date(self, date):
        return (
            self.gamelog_set
                .filter(game__date__lte=date)
                .order_by('-game__date'))

    def game_logs_last_x_days(self, x, from_date=None):
        if not from_date:
            from_date = datetime.now().date()
        return self.game_logs_since_date(from_date - timedelta(days=x), from_date=from_date)

    def game_logs_last_x_games(self, x, from_date=None):
        if not from_date:
            from_date = datetime.now().date()
        return self.gamelog_set.filter(game__date__lte=from_date).order_by('-game__date')[:x]

    def game_logs_against_team(self, team):
        if isinstance(team, six.string_types):
            if len(team) <= 3:
                q = Q(game__away_team__short=team) | Q(game__home_team__short=team)
            else:
                q = Q(game__away_team__name=team) | Q(game__home_team__name=team)
        elif isinstance(team, Team):
            q = Q(game__away_team=team) | Q(game__home_team=team)
        else:
            q = Q(game__away_team__pk=team) | Q(game__home_team__pk=team)
        return self.gamelog_set.filter(q)

    def average_points(self, game_logs=None):
        if game_logs:
            game_logs = game_logs.filter(player=self)
        else:
            game_logs = self.gamelog_set.all()

        all_draft_king_points = [gl.draft_king_points for gl in game_logs]
        if all_draft_king_points:
            return round(sum(all_draft_king_points) / len(all_draft_king_points), 2)
        return 0

    def average_minutes(self, game_logs=None):
        if game_logs:
            game_logs = game_logs.filter(player=self)
        else:
            game_logs = self.gamelog_set.all()

        all_minutes = [gl.minutes for gl in game_logs]
        if all_minutes:
            return round(sum(all_minutes) / len(all_minutes), 2)
        return 0

    def average_ppm(self, game_logs=None):
        if game_logs:
            game_logs = game_logs.filter(player=self)
        else:
            game_logs = self.gamelog_set.all()

        avg_minutes = self.average_minutes(game_logs=game_logs)
        avg_points = self.average_points(game_logs=game_logs)
        if avg_minutes and avg_points:
            return round(avg_points / avg_minutes, 2)
        return 0

    def total_games_last_x_days(self, x):
        return len(self.stats_last_x_days(x))

    def game_logs_for_season(self, season):
        return GameLog.objects.filter(player=self, game__season=season)

    def estimated_points(self, opponent=None, date=None, salary=None):
        if date is None:
            date = datetime.now()
        game_logs_1 = self.game_logs_last_x_days(365, from_date=date - timedelta(days=1))
        game_logs_2 = self.game_logs_last_x_days(90, from_date=date - timedelta(days=1))
        game_logs_3 = self.game_logs_last_x_days(5, from_date=date - timedelta(days=1))

        return (self.average_points(game_logs=game_logs_1) * 0.5 + self.average_points(game_logs=game_logs_2) * 0.3 +
                self.average_points(game_logs=game_logs_3) * 0.2)


class GameLog(models.Model):
    player = models.ForeignKey('Player')
    game = models.ForeignKey('Game')
    team = models.ForeignKey('Team')
    dk_salary = models.IntegerField(null=True, blank=True)

    minutes = models.IntegerField()
    offensive_rebounds = models.IntegerField()
    defensive_rebounds = models.IntegerField()
    personal_fouls = models.IntegerField()
    assists = models.IntegerField()
    steals = models.IntegerField()
    blocks = models.IntegerField()
    turnovers = models.IntegerField()

    free_throws_made = models.IntegerField()
    free_throws_attempted = models.IntegerField()
    twos_made = models.IntegerField()
    twos_attempted = models.IntegerField()
    threes_made = models.IntegerField()
    threes_attempted = models.IntegerField()
    field_goals_made = models.IntegerField()

draftkings/basketball/views/contests.py
from django.views.generic import ListView, DetailView

from basketball.models import Contest


class ContestListView(ListView):

    model = Contest
    template_name = 'contest_list.html'


class ContestDetailView(DetailView):
    model = Contest
    template_name = 'contest_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ContestDetailView, self).get_context_data(**kwargs)
        context['payouts'] = context['object'].contestpayout_set.all().order_by('start')
        return context

draftkings/basketball/views/custom_lineup.py
from django import forms
from django.shortcuts import render
from django.views.generic.edit import FormView
from basketball.utils.dk_tools.salaries import SalaryFileManager

from basketball.models import Player, GameLog


class LineupForm(forms.Form):
    lineup = forms.CharField(widget=forms.Textarea, required=False)
    contest = forms.ChoiceField(choices=enumerate(SalaryFileManager.salary_files()))


class CustomLineupView(FormView):

    template_name = 'custom_lineup.html'
    form_class = LineupForm

    def players_from_lineup(self, lineup):
        if lineup:
            players = lineup.split(',')
            players = [player.strip() for player in players]
            players = [player for player in players if player]
            return Player.objects.filter(name__in=players)
        else:
            return Player.objects.all()

    def form_valid(self, form):
        lineup = form.cleaned_data['lineup']
        contest_id = form.cleaned_data['contest']

        players = self.players_from_lineup(lineup)
        contest = SalaryFileManager.salary_files()[int(contest_id)]
        date = contest.date()

        game_logs = []
        for player in players:
            try:
                ps = player.gamelog_set.get(game__date=date)
                ps.expected_points = player.estimated_points(date=date)
                game_logs.append(ps)
            except GameLog.DoesNotExist:
                ps = Foo()
                ps.expected_points = player.estimated_points(date=date)
                ps.player = player
                ps.draft_king_points = 0
                ps.minutes = 0
                game_logs.append(ps)
        return render(
            self.request,
            self.template_name,
            self.get_context_data(
                game_logs=game_logs,
                total_points=sum(stat.draft_king_points for stat in game_logs),
                total_points_avg=sum(stat.player.average_points(stat.player.game_logs_before_date(date)) for stat in game_logs),
                total_points_predicted=sum(stat.player.estimated_points(date=date) for stat in game_logs),
                total_playtime=sum(stat.minutes for stat in game_logs),
                total_playtime_avg=sum(stat.player.average_minutes(stat.player.game_logs_before_date(date)) for stat in game_logs),
            )
        )


class Foo(object):
    pass

draftkings/basketball/views/elo.py
from django import forms
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic.edit import FormView

from basketball.models import Team
from basketball.utils.elo import ELO


class ELOForm(forms.Form):
    elo_1 = forms.IntegerField(
        required=False,
        widget=forms.NumberInput(attrs={'class': 'form-control input-sm'}))
    elo_2 = forms.IntegerField(
        required=False,
        widget=forms.NumberInput(attrs={'class': 'form-control input-sm'}))

    team_1 = forms.ModelChoiceField(
        Team.objects.all().order_by('name'),
        required=False,
        widget=forms.Select(attrs={'class': 'form-control input-sm'}))
    team_2 = forms.ModelChoiceField(
        Team.objects.all().order_by('name'),
        required=False,
        widget=forms.Select(attrs={'class': 'form-control input-sm'}))


class ELOView(FormView):

    template_name = 'elo.html'
    form_class = ELOForm

    def form_valid(self, form):
        context = self.get_context_data()
        elo_1 = form.cleaned_data['elo_1']
        elo_2 = form.cleaned_data['elo_2']

        team_1 = form.cleaned_data['team_1']
        team_2 = form.cleaned_data['team_2']

        if all((elo_1, elo_2)):
            diff = elo_1 - elo_2
        elif all((team_1, team_2)):
            diff = team_1.elo - team_2.elo
        else:
            diff = 0

        context['elo_diff'] = diff
        context['elo_point_spread'] = round(ELO.point_spread(diff), 1)
        context['elo_win_prob'] = round(ELO.win_probability(diff), 3) * 100.0

        return render(self.request, self.template_name, context)

draftkings/basketball/views/home.py
from django.views.generic.base import TemplateView


class HomeView(TemplateView):

    template_name = 'home.html'

draftkings/basketball/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Basketball</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>

    {#graphing#}
    <link rel="stylesheet" type="text/css" href="{% static 'bower_components/nvd3/build/nv.d3.min.css' %}"/>

    <style>
    </style>

    {% block css %}
    {% endblock %}
</head>
<body>

{% block nav %}
    {% include 'nav.html' %}
{% endblock %}

<div id="block-container" class="container">
{% block content %}
{% endblock %}
</div>

<script type="text/javascript" src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bower_components/tether/dist/js/tether.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>

<script type="text/javascript" src="{% static 'bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>

{#graphing#}
<script type="text/javascript" src="{% static 'bower_components/d3/d3.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bower_components/nvd3/build/nv.d3.min.js' %}"></script>

{% block scripts %}
{% endblock %}

</body>
</html>

draftkings/basketball/templates/elo.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
<style>
.elo-form {
    margin-bottom: 32px;
}
h1 {
    margin-bottom: 32px;
}
</style>
{% endblock %}

{% block content %}
    <div class="">

        <h1>
            ELO calc
        </h1>

        <form class="form-inline elo-form" action="" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-sm-3">
                    <label for="id_elo_1">Team 1</label>
                    {{ form.team_1 }}
                </div>
                <div class="col-sm-3">
                    <label for="id_elo_2">Team 2</label>
                    {{ form.team_2 }}
                </div>
            </div>
            <h2 style="margin: 32px;">or</h2>
            <div class="row">
                <div class="col-sm-3">
                    <label for="id_elo_1">Team 1 ELO</label>
                    {{ form.elo_1 }}
                </div>
                <div class="col-sm-3">
                    <label for="id_elo_2">Team 2 ELO</label>
                    {{ form.elo_2 }}
                </div>
            </div>

            <input type="submit">
        </form>

        <div class="well well-lg">
            <div class="row">
                <div class="col-md-4">
                    <div class="row">
                        <div class="col-md-12">
                            <h3>Summary</h3>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            difference
                        </div>
                        <div class="col-md-6">
                            {{ elo_diff }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            point spread
                        </div>
                        <div class="col-md-6">
                            {{ elo_point_spread }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            win probability
                        </div>
                        <div class="col-md-6">
                            {{ elo_win_prob }}%
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

draftkings/basketball/templates/player_detail.html
{% extends 'base.html' %}

{% block css %}
    <style>
        #chart svg {
            height: 300px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="">

        <h1>
            {{ object.name }}
        </h1>

        <form class="form-inline" action="">
            <div class="form-group">
                <label for="id_season">Season</label>
                {{ filters.season }}
            </div>
        </form>

        <div id="chart">
            <svg></svg>
        </div>

        <div class="well well-lg">
            <div class="row">
                <div class="col-md-4">
                    <div class="row">
                        <div class="col-md-12">
                            <h3>Player</h3>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            Team:
                        </div>
                        <div class="col-md-6">
                            <a href="{% url 'team' object.current_team.pk %}">{{ object.current_team }}</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            Position:
                        </div>
                        <div class="col-md-6">
                            {{ object.position }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            Age:
                        </div>
                        <div class="col-md-6">
                            {{ object.age }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            Height:
                        </div>
                        <div class="col-md-6">
                            {{ object.height }} cm
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            Weight:
                        </div>
                        <div class="col-md-6">
                            {{ object.weight }} kg
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="row">
                        <div class="col-md-12">
                            <h3>Averages</h3>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            points:
                        </div>
                        <div class="col-md-6">
                            {{ average_points }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            minutes:
                        </div>
                        <div class="col-md-6">
                            {{ average_playtime }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            points/minute:
                        </div>
                        <div class="col-md-6">
                            {{ average_pts_per_min }}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <table class="table table-striped" style="font-size: .8em;">
            <thead>
            <tr>
                <th>Date</th>
                <th>Game</th>
                <th>Twos</th>
                <th>Threes</th>
                <th>Free Throws</th>
                <th>Assists</th>
                <th>Turnovers</th>
                <th>Steals</th>
                <th>Playtime</th>
                <th>DK Points</th>
                <th>Points/Min</th>
            </tr>
            </thead>
            <tbody>
            {% for gl in game_logs %}
                <tr>
                    <td>{{ gl.game.date|date:"SHORT_DATE_FORMAT" }}</td>
                    <td>
                        <a href="{% url 'game' gl.game.pk %}">{{ gl.game.home_team.abbreviation }}
                            v {{ gl.game.away_team.abbreviation }}</a>
                    </td>
                    <td>{{ gl.twos }}</td>
                    <td>{{ gl.threes }}</td>
                    <td>{{ gl.free_throws }}</td>
                    <td>{{ gl.assists }}</td>
                    <td>{{ gl.turnovers }}</td>
                    <td>{{ gl.steals }}</td>
                    <td>{{ gl.minutes }}</td>
                    <td>{{ gl.draft_king_points }}</td>
                    <td>{{ gl.points_per_min }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
{% endblock %}

{% block scripts %}
    <script>

        $('.table').DataTable({
            "paging": false,
            "bFilter": false
        });

        $("#id_season").change(function (e) {
            $(this).closest("form").submit();
        });

        function pWrap(value) {
            return '<p>' + value + '</p>';
        }

        var data = {{ data|safe }};

        nv.addGraph(function () {
            var chart = nv.models.lineChart().useInteractiveGuideline(true);

            chart.interactiveLayer.tooltip.contentGenerator(function (data) {
                var tt = '';
                tt += pWrap('game ' + data.series[0].data.x);
                tt += pWrap(data.series[0].data.game);
                tt += pWrap(data.series[0].data.elo_home);
                tt += pWrap(data.series[0].data.elo_away);

                for (var i = 0; i < data.series.length; i++) {
                    if (data.series[i].key == 'points') {
                        tt += pWrap('  points - ' + data.series[i].data.y);
                    }
                    else if (data.series[i].key == 'playtime') {
                        tt += pWrap('  play time - ' + data.series[i].data.y);
                    }
                }
                return tt;
            });
            chart.xAxis
                    .axisLabel('Game')
                    .tickFormat(d3.format(',r'));
            chart.yAxis
                    .axisLabel('DraftKing Points')
                    .tickFormat(d3.format('.02f'));
            d3.select('#chart svg')
                    .datum(data)
                    .transition().duration(500)
                    .call(chart);
            nv.utils.windowResize(chart.update);
            return chart;
        });
    </script>
{% endblock %}

draftkings/basketball/templates/team_detail.html
{% extends 'base.html' %}

{% load dk_tags %}

{% block css %}
    <style>
        #chart svg {
            height: 300px;
        }

        .ta-right {
            text-align: right;
        }
        .ta-center {
            text-align: center;
        }

    </style>
{% endblock %}

{% block content %}
    <div class="">

        <h1>
            {{ object.name }}
        </h1>

        <form class="form-inline" action="">
            <div class="form-group">
                <label for="id_season">Season</label>
                {{ filters.season }}
            </div>
        </form>

        <div id="chart">
            <svg></svg>
        </div>

        <div class="well well-lg">
            <div class="row">
                <div class="col-md-4">
                    <div class="row">
                        <div class="col-md-12 ta-center">
                            <h3>Averages</h3>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 ta-right">
                            points
                        </div>
                        <div class="col-md-6">
                            {{ average_points }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 ta-right">
                            minutes
                        </div>
                        <div class="col-md-6">
                            {{ average_playtime }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 ta-right">
                            pts/min
                        </div>
                        <div class="col-md-6">
                            {{ average_pts_per_min }}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <table class="table table-striped" style="font-size: .8em;">
            <thead>
            <tr>
                <th>Player</th>
                <th>Position</th>
                <th>Average Points</th>
                <th>Average Playtime</th>
                <th>Ave PPM</th>
                <th>Games</th>
            </tr>
            </thead>
            <tbody>
            {% for player in players %}
                <tr>
                    <td><a href="{% url 'player' player.pk %}">{{ player.name }}</a></td>
                    <td>{{ player.position }}</td>
                    <td>{% avg_pts_for_season player season %}</td>
                    <td>{% avg_mins_for_season player season %}</td>
                    <td>{% avg_ppm_for_season player season %}</td>
                    <td>{% game_count_for_season player season %}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
{% endblock %}

{% block scripts %}
    <script>

        $('.table').DataTable({
            "paging": false,
            "bFilter": false
        });

        $("#id_season").change(function (e) {
            $(this).closest("form").submit();
        });

        function pWrap(value) {
            return '<p>' + value + '</p>';
        }

        var data = {{ data|safe }};

        nv.addGraph(function () {
            var chart = nv.models.lineChart().useInteractiveGuideline(true);

            chart.interactiveLayer.tooltip.contentGenerator(function (data) {
                var tt = '';
                tt += pWrap('game ' + data.series[0].data.x);
                tt += pWrap(data.series[0].data.game);

                for (var i = 0; i < data.series.length; i++) {
                    if (data.series[i].key == 'points') {
                        tt += pWrap('  points - ' + data.series[i].data.y);
                    }
                    else if (data.series[i].key == 'playtime') {
                        tt += pWrap('  play time - ' + data.series[i].data.y);
                    }
                    else if (data.series[i].key == 'ELO') {
                        tt += pWrap('  ELO - ' + data.series[i].data.y);
                    }
                }
                return tt;
            });
            chart.xAxis
                    .axisLabel('Game')
                    .tickFormat(d3.format(',r'));
            chart.yAxis
                    .axisLabel('DraftKing Points')
                    .tickFormat(d3.format('.02f'));
{#            chart.yDomain([1100,1900]);#}
            d3.select('#chart svg')
                    .datum(data)
                    .transition().duration(500)
                    .call(chart);
            nv.utils.windowResize(chart.update);
            return chart;
        });
    </script>
{% endblock %}